app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  database-access-type: jpa
  use-queue: true

retry:
  type: exponential
  base-delay: 5
  max-attempts: 3
  status-codes: [ 429, 500, 501, 502, 503 ]

rate-limiting:
  bucket-size: 100
  tokens: 50
  refill-interval: 5m
  cache-duration: 15m

kafka:
  bootstrap-server: localhost:9092
  group-id: scrapper
  auto-offset-reset: earliest
  linger-ms: 10
  topic-name: update_topic


spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 80

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
