app:
  scheduler:
    enable: true
    interval: 1800s
    force-check-delay: 10s

spring:
  application:
    name: scrapper

server:
  port: 80

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
