app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  database-access-type: jdbc


spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

server:
  port: 80

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
