app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  database-access-type: jdbc

retry:
  type: exponential
  base-delay: 5
  max-attempts: 3
  status-codes: [ 429, 500, 501, 502, 503 ]

rate-limiting:
  bucket-size: 100
  tokens: 50
  refill-interval: 5m
  cache-duration: 15m


spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

server:
  port: 80

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
