app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  database-access-type: JPA

retry:
  type: exponential
  base-delay: 5
  max-attempts: 3
  status-codes: [ 429, 500, 501, 502, 503 ]

rate-limiting:
  capacity: 200
  refill-tokens: 20
  refill-interval: 5s

cache:
  maximum-size: 100
  expire-after-write: 15m
  expire-after-access: 10m
  eviction-strategy: LRU

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

server:
  port: 80

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
