app:
  telegram-token: 6466351131:AAGiqz0NpquSObip4t3NXN8FGC_grxrYI0s

retry:
  type: constant
  base-delay: 5
  max-attempts: 5
  status-codes: [ 429, 500, 501, 502, 503 ]

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
