app:
  telegram-token: ${TELEGRAM_TOKEN}
  use-queue: true

retry:
  type: constant
  base-delay: 5
  max-attempts: 5
  status-codes: [ 429, 500, 501, 502, 503 ]

kafka:
  bootstrap-server: localhost:9092
  group-id: group
  topic-name: update_topic
  concurrency: 3
  poll-timeout: 3000

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 90

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
